### ISSUE TITLE
Safari 15 not working

### ISSUE THREAD

**Issue by maticrivo** [fabiospampinato/phoenix#11]
Hey, i love your phoenix setup and i use it all the time, since updating to Safari 15 (using Safari Technology Preview) it stoped working and i can't make it to work.

is this a known issue?

**Comment by fabiospampinato** [comment]
What stopped working, everything? Like you updated to Safari 15 and you can't even position your windows around through Phoenix anymore? That's not a known issue.

**Comment by maticrivo** [comment]
the window positioning isn't working but only on safari, its working on all other apps
Mac OS: 11.4
Phoenix version: 2.6.7

**Comment by fabiospampinato** [comment]
I see 🤔 No idea why that's the case. That's probably an upstream bug, in any case I don't have access to Safari 15 right now so I can't try to debug this.

**Comment by maticrivo** [comment]
If you have a mac running macOS 11+ you can try the latest Safari version using [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/)

**Comment by fabiospampinato** [comment]
I know, but I don't have a mac with Big Sur yet.

**Comment by maticrivo** [comment]
I'll try debugging and maybe opening a ticket to the phoenix repo itself, im pretty sure it's not a problem with your config 🙃

**Comment by maticrivo** [comment]
Seems to be fixed on the latest Safari Technology Preview release, might have been a problem on Apple's side 🙂
