### ISSUE TITLE
Center window on multiple screens always puts the window on the first screen.

### ISSUE THREAD

**Issue by ph1l337** [fabiospampinato/phoenix#2]
to fix change in `helpers/center_window.js` 

line 11 and 12 from 
```
    x: ( sFrame.width / 2 ) - ( wFrame.width / 2 ),
    y: ( sFrame.height / 2 ) - ( wFrame.height / 2 ),
```

to

```
    x: sFrame.x + ( sFrame.width / 2 ) - ( wFrame.width / 2 ),
    y: sFrame.y + ( sFrame.height / 2 ) - ( wFrame.height / 2 ),
```

With that fix though I have found still one issue - if the main screen is not centered relative to the peripheral screen, it is not exactly centered, but offset slightly. - But that's probably not an issue of the config, but rather phoenix itself.

**Comment by fabiospampinato** [comment]
Thanks for opening the issue.

Can you check if the other shortcuts provided by this configuration work in a multi-monitor setup?

**Comment by fabiospampinato** [comment]
I've improved multi-monitor support. Although I've found many other issues with it, I think those may happen if the monitors are arranged weirdly or if they don't all have the same resolution. 

Closing this in favor of #3.
