### ISSUE TITLE
It fails with Karabiner-Elements 12.10

### ISSUE THREAD

**Issue by maa3x** [fabiospampinato/phoenix#4]
Just the arrow keys and `space` works, but the others not.
Works with KE 12.0.0.

**Comment by fabiospampinato** [comment]
It's working just fine for me.

What do you mean only the arrow keys and `space` work, what's exactly is broken for you?

**Comment by maa3x** [comment]
Works in both versions:
```
caps + space
caps + up arrow
caps + right arrow
caps + bottom arrow
caps + left arrow
```
Works in 12.0.0 but does not work with KE 12.10:
```
caps + q
caps + w
caps + a
caps + s
caps + shift + q
caps + shift + w
caps + shift + e
caps + shift + a
caps + shift + s
caps + shift + d
caps + 1
caps + 2
caps + 3
caps + [
caps + ]
caps + x
caps + shift + x
```
The latter hotkeys stopped working when I upgraded KE to 12.10 and is now working again as I downgraded to 12.0.0.

**Comment by fabiospampinato** [comment]
They are still working for me 🤔 What version of macOS are you on?

**Comment by maa3x** [comment]
macOS HighSierra 10.13.4

**Comment by fabiospampinato** [comment]
I'm on v10.13.5, maybe they fixed a bug there.

I don't know how to help you, you can try rebooting 🤷‍♂️

I'm keeping this open though, maybe it's also happening to other peoples too.
