### ISSUE TITLE
Could you share your goku configuration for karabiner?

### ISSUE THREAD

**Issue by linuxbandit** [fabiospampinato/phoenix#7]
Hi,

I saw there's no dotfiles repo in your profile and i was wondering whether you could share the goku config to integrate into mine, instead of importing yours (which may collide with some of my config)

thank you!

**Comment by fabiospampinato** [comment]
I don't have one, I only use [this](https://github.com/fabiospampinato/phoenix/blob/master/config/karabiner.json) config.

**Comment by linuxbandit** [comment]
ah it's great! thank you
